### ISSUE TITLE
Peer-to-peer code review - 31/08

### ISSUE THREAD

**Issue by dicodiaz** [mike2611/portfolio#10]
Hello @mike2611, this issue is for feedback on the morning session peer-to-peer code review on 31/08.

**Comment by KatIsCoding** [comment]
### Pretty good job so far!! 🎉🎉
### Your project have none or almost no errors so it is kinda hard to review yours since I don't have almost any suggestion (anyways that's great haha)

### A small suggestion I would do is, instead of creating new CSS classes for `display: none` and `display: flex` what about using them inside your javascript so you don't have to "toggle".
### Other than that, great job!
![Gif](https://media.giphy.com/media/11c7UUfN4eoHF6/giphy.gif)

**Comment by ramiaquista** [comment]
## Awesome Project! 😄 

#### I think it would be a good idea if you avoid committing empty files to make it cleaner and easier for one who has to read! 

![Screen Shot 2021-08-31 at 11 24 32 AM](https://user-images.githubusercontent.com/24655018/131520324-5ca9cf7d-48ae-4fd7-b279-144afceaf734.png)

You have done a great job, keep up coding!  🎉 🎉

![cat-gift](https://camo.githubusercontent.com/ad1cd31d21b84078086e8649cd649f282fff8e3ee6636875934569562d21c8d6/68747470733a2f2f6d656469612e67697068792e636f6d2f6d656469612f3156694c7030474259685463412f67697068792e676966)

**Comment by dicodiaz** [comment]
Outstanding job! I have nothing to suggest for your last project's code.

However, I would recommend adding more information to your README file to make it more professional. You can find a really professional README from one of our more advanced fellow Microverse students [here](https://github.com/DanteAlonsoHT/OnlineCourse-FInalCapstone).

Keep up the good work!

**Comment by mike2611** [comment]
Thanks, partners I already applied your recommendations
